image: python:3.10

pipelines:
  default:
    - step:
        name: samlib
        caches:
          - pip
        script:
          - pip install 'mypy>=0.740'
          - mypy samlib --junit-xml test-reports/mypy.xml
  custom:
    build-manylinux2010_x86_64:  &manylinux2010_x86_64
      - step:
          image: quay.io/pypa/manylinux2010_x86_64
          script:
            - SSC_BUILD_DIR="$PWD/build" SSC_BUILD_JOBS="$(nproc)" PLATFORM_NAME="$AUDITWHEEL_PLAT" /opt/python/cp37-cp37m/bin/python -m build
            - SSC_BUILD_DIR="$PWD/build" SSC_BUILD_JOBS="$(nproc)" PLATFORM_NAME="$AUDITWHEEL_PLAT" /opt/python/cp38-cp38/bin/python -m build
            - SSC_BUILD_DIR="$PWD/build" SSC_BUILD_JOBS="$(nproc)" PLATFORM_NAME="$AUDITWHEEL_PLAT" /opt/python/cp39-cp39/bin/python -m build
            - SSC_BUILD_DIR="$PWD/build" SSC_BUILD_JOBS="$(nproc)" PLATFORM_NAME="$AUDITWHEEL_PLAT" /opt/python/cp310-cp310/bin/python -m build
          artifacts:
            - dist/**

definitions:
  caches:
    pip: ~/.cache/pip
